import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { validateHexMapAsset, type HexMapValidationResult } from "../../../packages/core/src/hex-engine/map/hex-map-validator";
import {
  hexCellSchema,
  hexLevelSchema,
  hexMapApModelSchema,
  hexMapGridSchema,
  hexRouteHintSchema,
  hexVerticalLinkSchema,
  type HexMapAsset
} from "../../../packages/shared/src/hex-schemas";
import { findProjectRoot } from "./server-project-root";

const supportedMapSlug = "dust2";
const hexAssetRelativePaths = {
  draft: "data/materials/processed/maps/dust2/hex/dust2-hex-map.draft.json",
  agent_refined: "data/materials/processed/maps/dust2/hex/dust2-hex-map.agent-refined.json"
} as const;
export type HexEditorMapVariant = keyof typeof hexAssetRelativePaths;
export const hexEditorMapVariants: Array<{ variant: HexEditorMapVariant; label: string; editable: boolean; description: string }> = [
  {
    variant: "draft",
    label: "当前草稿",
    editable: true,
    description: "你的主编辑草稿。保存 JSON 默认写入这里。"
  },
  {
    variant: "agent_refined",
    label: "Agent 完善副本",
    editable: true,
    description: "基于当前草稿生成的审计副本，补充 Dust2 区域、点位和参考路线。"
  }
];
const regionTypes = new Set(["a_site", "b_site", "mid", "long", "tunnel", "spawn", "rotate", "connector", "other"]);
const pointTypes = new Set(["spawn", "bombsite", "choke", "cover", "angle", "default", "route", "utility", "other"]);

export interface HexEditorMapPayload {
  asset: HexMapAsset;
  validation: HexMapValidationResult;
  path: string;
  variant: HexEditorMapVariant;
  variants: typeof hexEditorMapVariants;
}

export async function loadHexEditorMap(
  mapSlug = supportedMapSlug,
  projectRoot = findProjectRoot(),
  variant: HexEditorMapVariant = "draft"
): Promise<HexEditorMapPayload> {
  assertSupportedMapSlug(mapSlug);
  const resolvedVariant = assertSupportedVariant(variant);
  const assetPath = getHexEditorDraftPath(projectRoot, resolvedVariant);

  let raw: string | null = null;
  try {
    raw = await readFile(assetPath, "utf8");
  } catch (error) {
    if (!isMissingFileError(error)) {
      throw error;
    }
  }

  const asset = raw ? parseHexEditorMapAsset(JSON.parse(raw)) : createEmptyDust2HexDraft();
  return {
    asset,
    validation: validateHexEditorDraft(asset),
    path: assetPath,
    variant: resolvedVariant,
    variants: hexEditorMapVariants
  };
}

export async function saveHexEditorMap(
  input: unknown,
  mapSlug = supportedMapSlug,
  projectRoot = findProjectRoot(),
  variant: HexEditorMapVariant = "draft"
): Promise<HexEditorMapPayload> {
  assertSupportedMapSlug(mapSlug);
  const resolvedVariant = assertSupportedVariant(variant);
  const asset = parseHexEditorMapAsset(input);
  if (asset.mapSlug !== supportedMapSlug) {
    throw new HexEditorMapError("unsupported_map_slug", `Hex editor can only save ${supportedMapSlug}.`);
  }

  const normalizedAsset = pruneInvalidRouteHints(sortHexMapAsset(asset));
  const validation = validateHexEditorDraft(normalizedAsset);
  if (validation.errors.length > 0) {
    throw new HexEditorValidationError(validation);
  }

  const assetPath = getHexEditorDraftPath(projectRoot, resolvedVariant);
  await mkdir(dirname(assetPath), { recursive: true });
  await writeFile(assetPath, `${JSON.stringify(normalizedAsset, null, 2)}\n`, "utf8");

  return {
    asset: normalizedAsset,
    validation,
    path: assetPath,
    variant: resolvedVariant,
    variants: hexEditorMapVariants
  };
}

export function createEmptyDust2HexDraft(): HexMapAsset {
  return {
    schemaVersion: 1,
    mapSlug: supportedMapSlug,
    displayName: "Dust2 Hex Draft",
    grid: {
      width: 50,
      height: 50,
      coordinateSystem: "col_row",
      origin: "top_left"
    },
    apModel: {
      baseApPerPhase: 3,
      minAp: 0,
      cellsPerAp: 10,
      allowFractionalAp: true,
      resetsEachPhase: true
    },
    levels: [-1, 0, 1],
    defaultLevel: 0,
    cells: [],
    regions: [],
    points: [],
    routeHints: [],
    verticalLinks: [],
    notes: ["Generated by HexMapEditor. Fill playable cells, regions, points, and required flags before runtime use."]
  };
}

export function sortHexMapAsset(asset: HexMapAsset): HexMapAsset {
  return {
    ...asset,
    cells: [...asset.cells].sort(
      (left, right) => left.level - right.level || left.row - right.row || left.col - right.col || left.cellId.localeCompare(right.cellId)
    ),
    regions: [...asset.regions].sort((left, right) => left.regionId.localeCompare(right.regionId)),
    points: [...asset.points].sort((left, right) => left.pointId.localeCompare(right.pointId)),
    routeHints: [...asset.routeHints].sort((left, right) => left.routeId.localeCompare(right.routeId)),
    verticalLinks: [...asset.verticalLinks].sort((left, right) => left.linkId.localeCompare(right.linkId)),
    notes: [...asset.notes]
  };
}

export function validateHexEditorDraft(asset: HexMapAsset): HexMapValidationResult {
  const validation = validateHexMapAsset(asset);
  const draftWarningCodes = new Set(["route_unknown_cell", "route_unknown_point"]);
  const routeWarnings = validation.errors.filter((issue) => draftWarningCodes.has(issue.code));
  const hardErrors = validation.errors.filter((issue) => !draftWarningCodes.has(issue.code));

  return {
    ok: hardErrors.length === 0,
    errors: hardErrors,
    warnings: [...validation.warnings, ...routeWarnings]
  };
}

export function pruneInvalidRouteHints(asset: HexMapAsset): HexMapAsset {
  const cellIds = new Set(asset.cells.map((cell) => cell.cellId));
  const pointIds = new Set(asset.points.map((point) => point.pointId));
  return {
    ...asset,
    routeHints: asset.routeHints.filter(
      (route) =>
        pointIds.has(route.fromPointId) &&
        pointIds.has(route.toPointId) &&
        route.viaCellIds.every((cellId) => cellIds.has(cellId))
    )
  };
}

export function getHexEditorDraftPath(projectRoot = findProjectRoot(), variant: HexEditorMapVariant = "draft"): string {
  return resolve(projectRoot, hexAssetRelativePaths[assertSupportedVariant(variant)]);
}

export function parseHexEditorMapAsset(input: unknown): HexMapAsset {
  if (!isRecord(input)) {
    throw new HexEditorMapError("hex_map_schema_invalid", "Hex editor draft must be an object.");
  }

  const schemaVersion = input.schemaVersion;
  if (schemaVersion !== 1) {
    throw new HexEditorMapError("hex_map_schema_invalid", "Hex editor draft schemaVersion must be 1.");
  }

  const mapSlug = requireString(input.mapSlug, "mapSlug");
  const displayName = requireString(input.displayName, "displayName");
  const grid = hexMapGridSchema.parse(input.grid);
  const apModel = hexMapApModelSchema.parse(input.apModel);
  const rawLevels = readArray(input.levels, "levels");
  const levels: HexMapAsset["levels"] =
    rawLevels.length > 0 ? (rawLevels.map((level) => hexLevelSchema.parse(level)) as HexMapAsset["levels"]) : [-1, 0, 1];
  const defaultLevel: HexMapAsset["defaultLevel"] = input.defaultLevel === undefined ? 0 : hexLevelSchema.parse(input.defaultLevel);
  const cells = readArray(input.cells, "cells").map((cell, index) => parseEditorCell(cell, index));
  const regions = readArray(input.regions, "regions").map((region, index) => parseEditorRegion(region, index));
  const points = readArray(input.points, "points").map((point, index) => parseEditorPoint(point, index));
  const routeHints = readArray(input.routeHints, "routeHints").map((routeHint, index) => parseEditorRouteHint(routeHint, index));
  const verticalLinks = readArray(input.verticalLinks, "verticalLinks").map((verticalLink, index) => parseEditorVerticalLink(verticalLink, index));
  const notes = readArray(input.notes, "notes").map((note, index) => requireString(note, `notes.${index}`));

  return {
    schemaVersion,
    mapSlug,
    displayName,
    grid,
    apModel,
    levels,
    defaultLevel,
    cells,
    regions,
    points,
    routeHints,
    verticalLinks,
    notes
  };
}

export interface ZodLikeError {
  issues: Array<{
    path: Array<string | number>;
    message: string;
  }>;
}

export function isZodLikeError(error: unknown): error is ZodLikeError {
  return (
    typeof error === "object" &&
    error !== null &&
    "issues" in error &&
    Array.isArray((error as { issues?: unknown }).issues)
  );
}

export function formatZodError(error: ZodLikeError): string {
  return error.issues.map((issue) => `${issue.path.join(".") || "asset"}: ${issue.message}`).join("; ");
}

export class HexEditorMapError extends Error {
  constructor(
    public readonly code: string,
    message: string
  ) {
    super(message);
    this.name = "HexEditorMapError";
  }
}

export class HexEditorValidationError extends Error {
  constructor(public readonly validation: HexMapValidationResult) {
    super("Hex map asset has validation errors.");
    this.name = "HexEditorValidationError";
  }
}

function assertSupportedMapSlug(mapSlug: string): void {
  if (mapSlug !== supportedMapSlug) {
    throw new HexEditorMapError("unsupported_map_slug", `Hex editor only supports ${supportedMapSlug}.`);
  }
}

function assertSupportedVariant(variant: string): HexEditorMapVariant {
  if (variant === "draft" || variant === "agent_refined") {
    return variant;
  }
  throw new HexEditorMapError("unsupported_map_variant", `Hex editor does not support map variant: ${variant}`);
}

function isMissingFileError(error: unknown): boolean {
  return typeof error === "object" && error !== null && "code" in error && (error as { code?: string }).code === "ENOENT";
}

function parseEditorRegion(input: unknown, index: number): HexMapAsset["regions"][number] {
  if (!isRecord(input)) {
    throw new HexEditorMapError("hex_map_schema_invalid", `regions.${index} must be an object.`);
  }
  const regionType = requireString(input.regionType, `regions.${index}.regionType`);
  if (!regionTypes.has(regionType)) {
    throw new HexEditorMapError("hex_map_schema_invalid", `regions.${index}.regionType is not supported: ${regionType}`);
  }

  return {
    regionId: requireString(input.regionId, `regions.${index}.regionId`),
    nameCn: requireString(input.nameCn, `regions.${index}.nameCn`),
    nameEn: requireString(input.nameEn, `regions.${index}.nameEn`),
    regionType: regionType as HexMapAsset["regions"][number]["regionType"],
    cellIds: readArray(input.cellIds, `regions.${index}.cellIds`).map((cellId, cellIndex) =>
      migrateCellRef(requireString(cellId, `regions.${index}.cellIds.${cellIndex}`))
    ),
    businessSemantics: input.businessSemantics === undefined ? undefined : requireString(input.businessSemantics, `regions.${index}.businessSemantics`)
  };
}

function parseEditorPoint(input: unknown, index: number): HexMapAsset["points"][number] {
  if (!isRecord(input)) {
    throw new HexEditorMapError("hex_map_schema_invalid", `points.${index} must be an object.`);
  }
  const pointType = requireString(input.pointType, `points.${index}.pointType`);
  if (!pointTypes.has(pointType)) {
    throw new HexEditorMapError("hex_map_schema_invalid", `points.${index}.pointType is not supported: ${pointType}`);
  }

  return {
    pointId: requireString(input.pointId, `points.${index}.pointId`),
    nameCn: requireString(input.nameCn, `points.${index}.nameCn`),
    nameEn: requireString(input.nameEn, `points.${index}.nameEn`),
    pointType: pointType as HexMapAsset["points"][number]["pointType"],
    parentRegionId: requireString(input.parentRegionId, `points.${index}.parentRegionId`),
    cellIds: readArray(input.cellIds, `points.${index}.cellIds`).map((cellId, cellIndex) =>
      migrateCellRef(requireString(cellId, `points.${index}.cellIds.${cellIndex}`))
    )
  };
}

function parseEditorCell(input: unknown, index: number): HexMapAsset["cells"][number] {
  if (!isRecord(input)) {
    throw new HexEditorMapError("hex_map_schema_invalid", `cells.${index} must be an object.`);
  }
  const level = input.level === undefined ? 0 : hexLevelSchema.parse(input.level);
  const cellId = migrateCellIdForLevel(requireString(input.cellId, `cells.${index}.cellId`), level);

  return hexCellSchema.parse({
    ...input,
    cellId,
    level,
    pointIds: readArray(input.pointIds, `cells.${index}.pointIds`).map((pointId, pointIndex) =>
      requireString(pointId, `cells.${index}.pointIds.${pointIndex}`)
    )
  });
}

function parseEditorRouteHint(input: unknown, index: number): HexMapAsset["routeHints"][number] {
  if (!isRecord(input)) {
    throw new HexEditorMapError("hex_map_schema_invalid", `routeHints.${index} must be an object.`);
  }
  return hexRouteHintSchema.parse({
    ...input,
    viaCellIds: readArray(input.viaCellIds, `routeHints.${index}.viaCellIds`).map((cellId, cellIndex) =>
      migrateCellRef(requireString(cellId, `routeHints.${index}.viaCellIds.${cellIndex}`))
    )
  });
}

function parseEditorVerticalLink(input: unknown, index: number): HexMapAsset["verticalLinks"][number] {
  if (!isRecord(input)) {
    throw new HexEditorMapError("hex_map_schema_invalid", `verticalLinks.${index} must be an object.`);
  }
  return hexVerticalLinkSchema.parse({
    ...input,
    fromCellId: migrateCellRef(requireString(input.fromCellId, `verticalLinks.${index}.fromCellId`)),
    toCellId: migrateCellRef(requireString(input.toCellId, `verticalLinks.${index}.toCellId`))
  });
}

function migrateCellIdForLevel(cellId: string, level: HexMapAsset["cells"][number]["level"]): string {
  return /^h_\d{2}_\d{2}$/.test(cellId) ? `${cellId}_l${level}` : cellId;
}

function migrateCellRef(cellId: string): string {
  return /^h_\d{2}_\d{2}$/.test(cellId) ? `${cellId}_l0` : cellId;
}

function readArray(value: unknown, path: string): unknown[] {
  if (value === undefined) {
    return [];
  }
  if (!Array.isArray(value)) {
    throw new HexEditorMapError("hex_map_schema_invalid", `${path} must be an array.`);
  }
  return value;
}

function requireString(value: unknown, path: string): string {
  if (typeof value !== "string" || value.length === 0) {
    throw new HexEditorMapError("hex_map_schema_invalid", `${path} must be a non-empty string.`);
  }
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
